name: Build and Deploy Code

# on:
#  push:
#    branches:
#      - "main"
#      - "feature"
#  pull_request:
#    branches:
#      - "test_branch" 
on: [push, pull_request]

jobs:
  job1: 
    runs-on: ubuntu-latest
    steps:
      - name: Pulling git repo
        uses: actions/checkout@v2
      - name: Say hi to James
        run: echo "Hello James"